<a href="https://colab.research.google.com/github/joshuacharlesp1998/joshuacharlesp1998/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install lazypredict

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split as split

In [5]:
sample_data/

SyntaxError: ignored

In [7]:
from tkinter import *
import datetime
import time


In [16]:
def alarm(set_alarm_timer):
    while True:
      current_time=datetime.datetime.now()
      now=current_time.strftime("%H:%M:%S")
      date=current_time.strftime("%d/%m/%y")
      print("The set date is", date)
      print(now)
      if now == set_alarm_timer:
        print("Time to Wake up")
      break


def actual_time():
  set_alarm_timer= f"{hour.get()}:{min.get()}:{sec.get()}"
  alarm(set_alarm_timer)

In [2]:
import tensorflow as tf  
  
tpu = tf.distribute.cluster_resolver.TPUClusterResolver()    
print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])  

ValueError: ignored

In [3]:
import numpy as np

In [9]:
np.zeros((100,100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [21]:
np.arange(-1009,100,1)

array([-1009, -1008, -1007, ...,    97,    98,    99])

In [40]:
np.random.randint(998,1000,100)

array([998, 998, 998, 999, 998, 999, 998, 998, 998, 999, 998, 999, 999,
       999, 999, 998, 998, 998, 999, 999, 998, 999, 998, 999, 998, 999,
       998, 998, 999, 999, 998, 999, 999, 998, 999, 999, 999, 998, 998,
       999, 998, 999, 999, 999, 999, 998, 999, 999, 999, 999, 999, 999,
       999, 998, 998, 999, 999, 999, 998, 998, 998, 998, 998, 999, 999,
       998, 999, 998, 999, 998, 999, 998, 999, 998, 999, 999, 999, 999,
       999, 998, 999, 999, 998, 999, 998, 998, 999, 999, 998, 999, 998,
       999, 998, 998, 999, 998, 998, 998, 998, 999])

In [43]:
np.array([9999,9999])

array([9999, 9999])

In [47]:
np.full((3,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [48]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [49]:
np.random.randint(1,20,2)

array([11,  4])

In [52]:
n1=np.random.randint(1,20,4)
n2=np.random.randint(1,10,4)
n1

array([11,  9,  6, 16])

In [53]:
n2

array([6, 7, 5, 7])

In [54]:
np.sum([n1+n2])

67

In [56]:
np.sum([n1+n2],axis=1)

array([67])

In [61]:
a=np.array([9,3,4,5,6,7,8,2],ndmin=3)
a   


array([[[9, 3, 4, 5, 6, 7, 8, 2]]])

In [63]:
np.repeat([1,2,3,4],5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4])

In [66]:
np.tile([1,2,3],5)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])